source("Functions_actual.R")
nr_locations <- 5 # Number of distinct locations

geodistance <- matrix(nrow=nr_locations, ncol=nr_locations) # Associate with each pair of coordinates a "distance"


for (i in 1:nr_locations) {
  geodistance[i,i] <- 0 # Distance to itself always 0
  if (i<nr_locations) {
    for (j in ((i+1):nr_locations)) {
      geodistance[i,j] <- 1 # Simplified case: all distinct locations with distance 1
    }
  }
  if (i>1) {
    for (j in 1:(i-1)) {
      geodistance[i,j]=geodistance[j,i] # Distance needs to be symmetric
    }
  }
}

popsize_init <- 5302000 # Initial population size
calendar_time <- 1975 # Calendar time at beginning


initialprevalence <-0.01* 0.00076 # Assumption equivalent to deterministic model
malehighrisk <- 0.1
femalehighrisk <- 0.05

#population <- matrix(list(), nrow=popsize_init, ncol=8) 
HIVdata <- matrix(0, nrow=0, ncol=19) # Create a matrix for HIV infected individuals (each row, one patient)

year <- calendar_time # Current year

population <- matrix(0, nrow=popsize_init, ncol=13) # Create a matrix for the population: each row corresponds to one individual, each column one indicator

population[,1] <- (1:popsize_init) # Column 1: Individual ID
population[,2] <- runif(popsize_init, 0, 60) # Column 2: age in years at the beginning of the year
population[,3] <- rbinom(popsize_init, 1, 0.5) # Column 3: sex (0=male, 1=female)
population[,4] <- sample(nr_locations, popsize_init, replace=TRUE) # Column 4: current location of the individual at the beginning of the year
# (Column 5: distal factor 1, currently not used)
population[,6] <- rbinom(popsize_init, 1, population[,3]*(population[,2]>=15 & population[,3]<40)*malehighrisk + (1-population[,3])*(population[,2]>=15 & population[,2]<25)*femalehighrisk) # Column 6: proximal factor 1: high-risk behaviour
population[,7] <- rbinom(popsize_init, 1, 0) # Column 7: proximal factor 2: currently empty
population[,8] <- rbinom(popsize_init, 1, initialprevalence) # Column 8: HIV infected: yes or no
population[,9] <- population[,8]*(year-runif(popsize_init, 0, 2)) + (1-population[,8])*10000 # Coulmn 9: Time of HIV infection (this approach only applied in the fist year, assuming infection within past 2 years)
newinfected <- population[,8] # Newly infected by HIV
newpat_id <- population[which(population[,8]==1),1] # IDs of HIV infected
infyear <- population[which(population[,8]==1),9] # Times of infection
source("HIVsimulation_var1.R") # Run HIV simulation for all infected individuals
population[(which(population[,8]==1)),10] <- apply((HIVdata[,(2:19)]*(HIVdata[,(2:19)]<=population[(which(population[,8]==1)),9])), 1, which.max) # Column 10: State at which each HIV infected patien is at the beginning of the year
population[,11] <- 1 #Column 11: alive or not at the beginning of the year

population[,13] <- partnerselect(population, year)

popsize_current <- popsize_init # Current population size

for (year in (1976:1980)) {

if (year >1976) {popsize_current <- popsize_updated}
population[,2] <- population[,2]+1 #Age: 1 year more

population[,4] <- relocate_var2(population[,4],year,population[,2],population[,3],population[,(6:7)],geodistance,popsize_current) # Check if relocates
population[,13] <- partnerselect(population, year) # Check if changes regular partner

population[,(6:7)] <- reassign_var1(population[,(6:7)],year,population[,2],population[,3],population[,4]) # Check if changes behaviour
population[,8] <- transmission_var3(population, geodistance, year) # Check who gets infected by HIV
newinfected <- (population[,8]==1 & population[,9]==10000) # Newly infected (yes/no)
newpat_id <- population[which(newinfected),1] # IDs of those newly infected
population[,9] <- population[,8]*(newinfected*(year+runif(popsize_current)) + ((1-newinfected)*(population[,9]))) + (1-population[,8])*10000 # Assign time of infection for those newly infected
infyear <- population[which(newinfected & population[,8]==1),9] # Times of infection (store for the simulator)
population[(which(population[,10]==19)),11] <- 0 # Change alive to dead for those who die of HIV
population[,11] <- pmin(population[,11], mortality_var1(population[,2], population[,3], population[,4], population[,c(6,7)])) # Check who dies of non-HIV related causes
if (sum(newinfected)>0) {source("HIVsimulation_var1.R")} # Run HIV simulator for those newly infected

population[(which(population[,8]==1)),10] <- apply((HIVdata[,(2:19)]*(HIVdata[,(2:19)]<=year)), 1, which.max) # Assign the current state of HIV infection for all infected patients from the "HIVdata" table, generated by the cohort simulators 


livebirths <- birth_var1(population[,2], population[,3]) # Vector of mothers that give live birth
population <- rbind(population, matrix(0, nrow=length(livebirths), ncol=13)) # Add rows for newborns
population[((popsize_current+1):nrow(population)),12] <- livebirths # Assign each newborn the ID of the mother
population[((popsize_current+1):nrow(population)),1] <- ((popsize_current+1):nrow(population)) # Assign ech newborn an ID
population[((popsize_current+1):nrow(population)),2] <- runif(length(livebirths), -1, 0) #Assign each newborn the age at the beginning of year (will be negative because the birth will occur later during the year)
population[((popsize_current+1):nrow(population)),3] <- rbinom(length(livebirths), 1, 0.5) #Assign each newborn a gender
population[((popsize_current+1):nrow(population)),4] <- population[livebirths,4] #Assign each newborn a location (identical to mother's location)
population[((popsize_current+1):nrow(population)),8] <- mtct_var1(length(livebirths), population) #Check which newborns will be infected by HIV
population[((popsize_current+1):nrow(population)),9] <- population[((popsize_current+1):nrow(population)),8]*(year-population[((popsize_current+1):nrow(population)),2])+ (1-population[((popsize_current+1):nrow(population)),8] )*10000 #For the newborns infected, assign the time of infection = time of birth
newinfected <- (population[,8]==1 & population[,9]==10000) # Which individuals (newborns) are newly infected
newpat_id <- population[which(newinfected),1] #IDs of those newly infected
infyear <- population[which(newinfected & population[,8]==1),9] # Times of infection
if (sum(newinfected)>0) {source("hivsimulation_var1.R")} # Run HIV simulator for those newly infected
population[(which(population[,8]==1)),10] <- apply((HIVdata[,(2:19)]*(HIVdata[,(2:19)]<=year)), 1, which.max) # If dies of HIV assign time of death
popsize_updated <- nrow(population) #Update the population size


}

